"""
GitHub Diff Summarizer Skill
============================

A reusable, well-documented AI skill for summarizing GitHub diffs.
Used by both the PR Reviewer and the Repo Health Agent.

Inputs:
    - diff_content (str): The raw git diff content
    - context (str, optional): Additional context about the change

Outputs:
    dict with keys:
        - summary (str): One-paragraph summary of what changed
        - files_changed (list[str]): List of files modified
        - change_type (str): "feature" | "bugfix" | "refactor" | "docs" | "test" | "config"
        - risk_level (str): "low" | "medium" | "high"
        - key_changes (list[str]): Bullet points of the most important changes

Example:
    from apps.ai.skills.github_diff_summarizer import summarize_diff

    result = summarize_diff(diff_text)
    print(result['data']['summary'])
    print(result['provider'])  # which AI provider served this
"""
import logging
from apps.ai.ai_client import generate_json

logger = logging.getLogger(__name__)

SKILL_NAME = "github-diff-summarizer"
SKILL_VERSION = "1.0.0"

SYSTEM_INSTRUCTION = """You are an expert code analyst. Summarize the given git diff concisely.

Analyze the diff and produce a JSON response with:
1. summary: A clear, one-paragraph description of what this diff does
2. files_changed: List of file paths that were modified
3. change_type: Categorize as "feature", "bugfix", "refactor", "docs", "test", or "config"
4. risk_level: Assess as "low" (safe, minor), "medium" (moderate changes), or "high" (breaking/critical)
5. key_changes: Array of 3-5 bullet-point descriptions of the most significant changes

Respond in valid JSON format:
{
  "summary": "...",
  "files_changed": ["file1.py", "file2.js"],
  "change_type": "feature",
  "risk_level": "medium",
  "key_changes": ["Added new API endpoint for...", "Refactored database query to..."]
}"""


def summarize_diff(diff_content, context=None):
    """
    Summarize a GitHub diff using the AI fallback chain.

    Args:
        diff_content (str): Raw git diff content
        context (str, optional): Additional context (PR title, description, etc.)

    Returns:
        dict: { "data": { parsed JSON response }, "provider": "nvidia"|"gemini"|"groq" }
    """
    prompt = f"Summarize this git diff:\n\n```diff\n{diff_content}\n```"
    if context:
        prompt += f"\n\nAdditional context: {context}"

    logger.info(f"[{SKILL_NAME}] Summarizing diff ({len(diff_content)} chars)")

    result = generate_json(prompt, system=SYSTEM_INSTRUCTION)

    logger.info(f"[{SKILL_NAME}] Summary generated by {result['provider']}")

    return result
